--liquibase formatted sql
--changeset zaitis:1

CREATE TABLE CAR (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
brand VARCHAR(50),
model VARCHAR(50),
plate VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE COMPANY (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
company_name VARCHAR(50) NOT NULL,
phone VARCHAR(15),
mail VARCHAR(50)
);

CREATE TABLE `USER` (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
surname VARCHAR(50),
mail VARCHAR(50),
password VARCHAR(50),
card_number VARCHAR(8),
phone VARCHAR(12),
role Varchar(10)
);

