CREATE TABLE CAR (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
brand VARCHAR(50),
model VARCHAR(50),
plate VARCHAR(20) NOT NULL UNIQUE,
PRIMARY KEY (id)
);

CREATE TABLE COMPANY (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
company_name VARCHAR(50) NOT NULL,
phone VARCHAR(15),
mail VARCHAR(50),
PRIMARY KEY (id)
);

CREATE TABLE PERSON (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
surname VARCHAR(50),
mail VARCHAR(50),
password VARCHAR(50),
PRIMARY KEY (id)
);

CREATE TABLE GATE_PASS (
id BIGINT AUTO_INCREMENT,
id_card VARCHAR(5) NOT NULL,
name VARCHAR(50),
surname VARCHAR(50),
phone VARCHAR(15),
person_id BIGINT,
car_id BIGINT,
company_id BIGINT,
accepted_date DATE,
PRIMARY KEY (id),
FOREIGN KEY (person_id) REFERENCES PERSON(id),
FOREIGN KEY (car_id) REFERENCES CAR(id),
FOREIGN KEY (company_id) REFERENCES COMPANY(id)
);